---
title: "4th down research"
author: "Ben Baldwin"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is an update of [the analysis that used to be stored here](https://github.com/guga31bb/fourth_calculator/blob/main/R/season_numbers.R). The idea is to show different ways of using the package to analyze 4th down decisions in hopes of inspiring others to try other things.

```{r setup}
library(nfl4th)
library(tidyverse)

load_season <- function(season) {
  nflfastR::load_pbp(season) %>%
  nfl4th::add_4th_probs() %>%
  dplyr::mutate(go = ifelse((rush == 1 | pass == 1) & !play_type_nfl %in% c("PUNT", "FIELD_GOAL"), 100, 0)) %>%
  return()
}

pbp_2020 <- load_season(2020)
```

```{r worst}
library(gt)
pbp_2020 %>%
  filter(
    go == 0,
    # they tried to go for it
    !(posteam == "ARI" & week == 3 & play_id == 2364)
  ) %>%
  mutate(
    defteam = if_else(posteam == home_team, away_team, home_team)
  ) %>%
  arrange(-go_boost) %>%
  mutate(rank = 1 : n()) %>%
  head(10) %>%
  select(rank, posteam, defteam, week, qtr, ydstogo, diff = score_differential, go_boost, desc) %>%
  gt() %>%
  cols_label(
    rank = "",
    posteam = "Team",
    defteam = "Opp",
    week = "Week",
    qtr = "Qtr",
    ydstogo = "YTG",
    diff = "Diff",
    desc = "Play",
    go_boost = "WP loss"
  ) %>%
  tab_style(
    style = cell_text(color = "black", weight = "bold"),
    locations = list(
      cells_row_groups(),
      cells_column_labels(everything())
    )
  ) %>% 
  text_transform(
    locations = cells_body(vars(posteam)),
    fn = function(x) web_image(url = paste0('https://a.espncdn.com/i/teamlogos/nfl/500/',x,'.png'))
  ) %>% 
  text_transform(
    locations = cells_body(vars(defteam)),
    fn = function(x) web_image(url = paste0('https://a.espncdn.com/i/teamlogos/nfl/500/',x,'.png'))
  ) %>% 
  cols_width(
    everything() ~ px(400),
    ) %>% 
  cols_width(
    vars(rank) ~ px(30),
    vars(posteam) ~ px(50),
    vars(defteam) ~ px(50),
    vars(week) ~ px(50),
    vars(diff) ~ px(50),
    vars(qtr) ~ px(50),
    vars(ydstogo) ~ px(50),
    vars(go_boost) ~ px(70)
  ) %>% 
  tab_options(
    row_group.border.top.width = px(3),
    row_group.border.top.color = "black",
    row_group.border.bottom.color = "black",
    table_body.hlines.color = "white",
    table.border.top.color = "black",
    table.border.top.width = px(1),
    table.border.bottom.color = "white",
    table.border.bottom.width = px(1),
    column_labels.border.bottom.color = "black",
    column_labels.border.bottom.width = px(2),
    row.striping.background_color = '#FFFFFF',
    row.striping.include_table_body = TRUE,
    table.background.color = '#F2F2F2',
    data_row.padding = gt::px(2),
    table.font.size = gt::px(16L)
  ) %>%
  fmt_number(
    columns = vars(go_boost), decimals = 1
  ) %>%
  cols_align(
    columns = 1:8,
    align = "center"
  ) %>% 
  tab_header(
    title = md(glue::glue("Worst kick decisions of 2020"))
  )
```
